// TANKS
var DIRECTION_UP = 'up';
var DIRECTION_LEFT = 'left';
var DIRECTION_DOWN = 'down';
var DIRECTION_RIGHT = 'right';

var TANK_TYPE_SLOW = 'slow';
var TANK_TYPE_FAST = 'fast';

var TANK_COLOR_GOLD = 'gold';
var TANK_COLOR_GREEN = 'green';
var TANK_COLOR_SILVER = 'silver';
var TANK_COLOR_RED = 'red';

// GEMS
var GEM_HELMET = 'helmet';
var GEM_CLOCK = 'clock';
var GEM_SHOVEL = 'shovel';
var GEM_STAR = 'star';
var GEM_GRENADE = 'grenade';
var GEM_TANK = 'tank';
var GEM_GUN = 'gun';

var ALL_GEMS = [GEM_HELMET, GEM_CLOCK, GEM_SHOVEL, GEM_STAR,
                GEM_GRENADE, GEM_TANK, GEM_GUN];

// LANDMARKS
var LANDMARK_BRICK = 'brick';
var LANDMARK_IRON = 'iron';
var LANDMARK_WATER = 'water';
var LANDMARK_GRASS = 'grass';
var LANDMARK_ICE = 'ice';
var LANDMARK_BASE = 'base';


var ALL_LANDMARKS_EXCEPT_BASE = [LANDMARK_BRICK, LANDMARK_IRON, LANDMARK_WATER, LANDMARK_GRASS];
var ALL_LANDMARKS = ALL_LANDMARKS_EXCEPT_BASE.concat(LANDMARK_ICE);

// sprite parameters
var SPRITE_URL = 'NES-BattleCity-Generate.png';
var SPRITE_WIDTH = 16;
var SPRITE_HEIGHT = 16;

// various parameters needed to extract the correct tank image from the sprite.
var STEP_OFFSET_SIZE = 16;

var DIRECTION_OFFSET_SIZE = 16 * 2;
var DIRECTION_TO_H_OFFSET = {};
DIRECTION_TO_H_OFFSET[DIRECTION_UP] = 0;
DIRECTION_TO_H_OFFSET[DIRECTION_LEFT] = 1;
DIRECTION_TO_H_OFFSET[DIRECTION_DOWN] = 2;
DIRECTION_TO_H_OFFSET[DIRECTION_RIGHT] = 3;

var TANK_TYPE_OFFSET_SIZE = 16 * 4;
var TANK_TYPE_TO_OFFSET = {};
TANK_TYPE_TO_OFFSET[TANK_TYPE_SLOW] = 0;
TANK_TYPE_TO_OFFSET[TANK_TYPE_FAST] = 1;

var TANK_COLOR_OFFSET_SIZE = 16 * 8;
var TANK_COLOR_TO_H_OFFSET = {};
TANK_COLOR_TO_H_OFFSET[TANK_COLOR_GOLD] = 0;
TANK_COLOR_TO_H_OFFSET[TANK_COLOR_GREEN] = 0;
TANK_COLOR_TO_H_OFFSET[TANK_COLOR_SILVER] = 1;
TANK_COLOR_TO_H_OFFSET[TANK_COLOR_RED] = 1;

var TANK_COLOR_TO_V_OFFSET = {};
TANK_COLOR_TO_V_OFFSET[TANK_COLOR_GOLD] = 0;
TANK_COLOR_TO_V_OFFSET[TANK_COLOR_GREEN] = 1;
TANK_COLOR_TO_V_OFFSET[TANK_COLOR_SILVER] = 0;
TANK_COLOR_TO_V_OFFSET[TANK_COLOR_RED] = 1;

// various parameters for locating the gems in the sprite
var GEM_INIT_H_OFFSET = 16 * 8 * 2;
var GEM_INIT_V_OFFSET = 16 * 7;

var GEM_H_OFFSET_SIZE = 16;
var GEM_TO_H_OFFSET = {};
GEM_TO_H_OFFSET[GEM_HELMET] = 0;
GEM_TO_H_OFFSET[GEM_CLOCK] = 1;
GEM_TO_H_OFFSET[GEM_SHOVEL] = 2;
GEM_TO_H_OFFSET[GEM_STAR] = 3;
GEM_TO_H_OFFSET[GEM_GRENADE] = 4;
GEM_TO_H_OFFSET[GEM_TANK] = 5;
GEM_TO_H_OFFSET[GEM_GUN] = 6;

// various parameters for locating the land marks
var LANDMARK_INIT_H_OFFSET = 16 * 8 * 2;
LANDMARK_TO_H_OFFSET = {};
LANDMARK_TO_H_OFFSET[LANDMARK_BRICK] = LANDMARK_INIT_H_OFFSET;
LANDMARK_TO_H_OFFSET[LANDMARK_IRON] = LANDMARK_INIT_H_OFFSET;
LANDMARK_TO_H_OFFSET[LANDMARK_WATER] = LANDMARK_INIT_H_OFFSET;
LANDMARK_TO_H_OFFSET[LANDMARK_GRASS] = LANDMARK_INIT_H_OFFSET + 16;
LANDMARK_TO_H_OFFSET[LANDMARK_ICE] = LANDMARK_INIT_H_OFFSET + 16 * 2;
LANDMARK_TO_H_OFFSET[LANDMARK_BASE] = LANDMARK_INIT_H_OFFSET + 16 * 3;

var LANDMARK_TO_V_OFFSET = {};
LANDMARK_TO_V_OFFSET[LANDMARK_BRICK] = 0;
LANDMARK_TO_V_OFFSET[LANDMARK_IRON] = 16;
LANDMARK_TO_V_OFFSET[LANDMARK_WATER] = 16 * 2;
LANDMARK_TO_V_OFFSET[LANDMARK_GRASS] = 16 * 2;
LANDMARK_TO_V_OFFSET[LANDMARK_ICE] = 16 * 2;
LANDMARK_TO_V_OFFSET[LANDMARK_BASE] = 16 * 2;
